// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  experience: dynamic(() => import("./Experience")),
  footer: dynamic(() => import("./Footer")),
  hero: dynamic(() => import("./Hero")),
  projects: dynamic(() => import("./Projects")),
  tech_stack: dynamic(() => import("./TechStack")),
};
